redis:
  # redis���ݿ�������Ĭ��Ϊ0��������ʹ������Ϊ3�����ݿ⣬������������ݿ��ͻ
  database: 3
  # redis��������ַ��Ĭ��Ϊlocalhost��
  host: localhost
  # redis�˿ڣ�Ĭ��Ϊ6379��
  port: 6379
  # redis�������루Ĭ��Ϊ�գ�
  password:
  # redis���ӳ�ʱʱ�䣨��λΪ���룩
  timeout: 1000
  # redis���ӳ�����
  jedis:
    pool:
      # ��������������Ĭ��Ϊ8��������ʾ���ޣ�
      max-active: 8
      # ��������������Ĭ��Ϊ8��������ʾ���ޣ�
      max-idle: 8
      # ��С������������Ĭ��Ϊ0����ֵֻ��Ϊ�����������ã�
      min-idle: 0
      # �����ӳ��л�ȡ�������ȴ�ʱ�䣨Ĭ��Ϊ-1����λΪ���룬������ʾ���ޣ�
      max-wait: -1